Sass 1163
hmrc/income-tax-employment-frontend pull request #104
Opened 2021-09-17 08:54 UTC by lz1kwn

### Description
Create fuel benefit for company car radio button EOY page

Add a link to the relevant story in Jira
[SASS-1163](https://jira.tools.tax.service.gov.uk/browse/SASS-1163)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of master?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current master that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of master?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2021-09-17 15:39 UTC, ina-tu requested changes
needs a rebase

2021-09-17 15:39 UTC, ina-tu commented on app/controllers/employment/CompanyCarFuelBenefitsController.scala
> +                    //                  TODO: Need to potentially update this to make a cya or something
TODO can be removed

2021-09-17 15:39 UTC, ina-tu commented on it/controllers/employment/CompanyCarFuelBenefitsControllerISpec.scala
> +        "Render the 'Did you receive car benefits' page with the correct content with no benefits data so no pre-filling" which {
test name can be changed to "car fuel benefits page"

2021-09-17 15:39 UTC, ina-tu commented on it/controllers/employment/CompanyCarFuelBenefitsControllerISpec.scala
> +        "Render the 'Did you receive car benefits' page with the correct content with cya data and the yes value pre-filled" which {
same here

2021-09-17 15:39 UTC, ina-tu commented on it/controllers/employment/CompanyCarFuelBenefitsControllerISpec.scala
> +        "Redirect the user to the overview page when theres no session data for that user" which {
test name can be changed to "redirect user to the check your benefits page"

2021-09-17 15:39 UTC, ina-tu commented on it/controllers/employment/CompanyCarFuelBenefitsControllerISpec.scala
> +          "redirects to the check your details page" in {
test name can be changed to check your benefits page

2021-09-17 15:39 UTC, ina-tu commented on it/controllers/employment/CompanyCarFuelBenefitsControllerISpec.scala
> +        "Redirect to overview page when theres no CYA data" which {
same here

2021-09-17 15:39 UTC, ina-tu commented on app/controllers/employment/CompanyCarFuelBenefitsController.scala
> +import models.employment.CarVanFuelModel
unused import

2021-09-17 15:39 UTC, ina-tu commented on app/controllers/employment/CompanyCarFuelBenefitsController.scala
> +import views.html.employment.{ CompanyCarFuelBenefitsView}
braces can be removed from import for CompanyCarFuelBenefitsView

2021-09-17 15:39 UTC, ina-tu commented on it/controllers/employment/CompanyCarFuelBenefitsControllerISpec.scala
> +  object CyaModel {
`object CyaModel` is not used and can be removed

2021-09-17 15:39 UTC, ina-tu commented on it/controllers/employment/CompanyCarFuelBenefitsControllerISpec.scala
> +  def emptyCarVanFuelModel: CarVanFuelModel =
emptyCarVanFuelModel is unused and can be removed

2021-09-20 09:28 UTC, lz1kwn commented on app/controllers/employment/CompanyCarFuelBenefitsController.scala
> +                    //                  TODO: Need to potentially update this to make a cya or something
removed TODO

2021-09-22 10:41 UTC, ina-tu approved these changes

2021-09-22 10:42 UTC, merged