Sass 1284
hmrc/income-tax-employment-frontend pull request #107
Opened 2021-09-17 17:17 UTC by HarryGull

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)

### Checklist PR Reviewer
##### Before Reviewing
- [ x]  Have you pulled the branch down?
- [ x]  Have you assigned yourself to the PR?
- [ x]  Have you moved the task to “in review” on JIRA?
- [x ]  Have you checked to ensure all dependencies are up to date?
- [x ]  Have you checked to ensure its been rebased against the current version of master?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current master that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of master?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2021-09-21 16:31 UTC, ina-tu requested changes

2021-09-21 16:31 UTC, ina-tu commented on app/views/employment/StillWorkingForEmployerView.scala.html
> +            content = None,
`content = None` can be removed. It's set to none in the input radio helper

2021-09-22 10:24 UTC, matt712 commented on test/services/RedirectServiceSpec.scala
> +        employerRef = Some("123/12345"), startDate = Some("2020-11-01"), cessationDateQuestion = Some(true), taxablePayToDate = Some(1),
It's listed in the employmentDetails of the CYA model

2021-09-23 09:49 UTC, ina-tu requested changes

2021-09-23 09:49 UTC, ina-tu commented on app/views/employment/CheckEmploymentDetailsView.scala.html
> +                if(employmentDetails.cessationDateQuestion.contains(true)){Some(messages("common.no"))} else {Some(messages("common.yes"))}},
I think the yes and no should be the other way around. When I clicked yes on the question form it displays as no on cya page

2021-09-23 12:03 UTC, ina-tu approved these changes

2021-09-23 12:04 UTC, ina-tu commented
waiting for journey tests to be reviewed

2021-09-23 13:35 UTC, merged