living accommodation employment benefits amount EOY page created
hmrc/income-tax-employment-frontend pull request #140
Opened 2021-10-19 14:10 UTC by matt712

### Description
Created living accommodation amount page

[SASS-1424](https://jira.tools.tax.service.gov.uk/browse/SASS-1319)

### Checklist PR Reviewer
##### Before Reviewing
- [x]  Have you pulled the branch down?
- [x]  Have you assigned yourself to the PR?
- [x]  Have you moved the task to “in review” on JIRA?
- [x]  Have you checked to ensure all dependencies are up to date?
- [x]  Have you checked to ensure its been rebased against the current version of master?

##### Whilst Reviewing
- [x]  Have you run the tests?
- [x]  Have you run the journey tests?
- [x]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [x]  Have you checked for merge conflicts or any changes in the current master that may affect the current pull request? i.e. does it need another rebase?
- [x]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [x]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [X]  Have you run the tests?
- [X]  Have you run the journey tests? (where applicable)
- [X]  Have you addressed warnings where appropriate?
- [X]  Have you rebased against the current version of master?
- [x]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2021-10-19 14:18 UTC, BenCosfordHMRC requested changes

2021-10-19 14:18 UTC, BenCosfordHMRC commented on it/controllers/benefits/LivingAccommodationBenefitAmountControllerISpec.scala
> +    "redirect to the check your benefits page when accommodationQuestion is Some(false) and it's not a prior submission" which {
redirect tests can be outside of the user scenarios loop

2021-10-20 15:03 UTC, ina-tu commented on conf/messages
> +benefits.livingAccommodationAmount.error.overMaximum.individual = Your total living accommodation benefit amount must be less than £100,000,000,000
the content for the errors don't have "total" in the messages

2021-10-20 15:04 UTC, ina-tu commented on conf/messages
> +benefits.livingAccommodationAmount.error.noEntry.agent = Enter your client’s total living accommodation benefit amount
same for agent messages

2021-10-20 15:23 UTC, ina-tu commented on app/controllers/benefits/LivingAccommodationBenefitAmountController.scala
> +              employment.employmentBenefits.flatMap(_.benefits.flatMap(_.accommodation))
should this be getting the accommodation in the new accommodation relocation model instead of the one in the regular benefits model?

2021-10-20 15:24 UTC, ina-tu commented on conf/messages.cy
> +benefits.livingAccommodationAmount.error.noEntry.individual = Enter your total living accommodation benefit amount
same here - the content for the errors don't have "total" in the messages

2021-10-20 15:26 UTC, ina-tu commented on it/controllers/benefits/LivingAccommodationBenefitAmountControllerISpec.scala
> +  def cya(isPriorSubmission: Boolean = true, benefits: Option[BenefitsViewModel]):
def cya isn't used and can be removed

2021-10-20 15:28 UTC, ina-tu commented on it/controllers/benefits/LivingAccommodationBenefitAmountControllerISpec.scala
> +    "redirect to the check your benefits page when accommodationQuestion is None and it's a prior submission" which {
test name can be updated to "redirect to living accommodation page..."

2021-10-20 15:32 UTC, ina-tu commented on it/controllers/benefits/LivingAccommodationBenefitAmountControllerISpec.scala
> +            insertCyaData(employmentUserData(isPrior = true, cyaModel("name", hmrc = true,
should isPrior be false?

2021-10-20 15:36 UTC, ina-tu commented on it/controllers/benefits/LivingAccommodationBenefitAmountControllerISpec.scala
> +    "redirect to the check your benefits page when accommodationQuestion is None and it's a prior submission" which {
test name can be updated to redirect to living accommodation page

2021-10-21 08:48 UTC, ina-tu commented on app/controllers/benefits/LivingAccommodationBenefitAmountController.scala
> +              employment.employmentBenefits.flatMap(_.benefits.flatMap(_.accommodation))
oh yeah it is, sorry

2021-10-21 10:18 UTC, ina-tu commented on it/controllers/benefits/LivingAccommodationBenefitAmountControllerISpec.scala
> +import controllers.benefits.routes.{AccommodationRelocationBenefitsController, LivingAccommodationBenefitAmountController, LivingAccommodationBenefitsController}
some unused imports

2021-10-21 10:19 UTC, ina-tu commented on test/models/employment/AccommodationRelocationModelSpec.scala
>      "return call to AccommodationRelocationBenefitsController when accommodationQuestion and accommodation not defined" in {
test name can be changed from AccommodationRelocationBenefitsController to LivingAccommodationBenefitAmountController

2021-10-21 10:31 UTC, ina-tu approved these changes

2021-10-21 10:44 UTC, merged