Sass 1528
hmrc/income-tax-employment-frontend pull request #167
Opened 2021-11-09 09:42 UTC by joeyymoore

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2021-11-09 16:07 UTC, HarryGull requested changes

2021-11-10 08:37 UTC, joeyymoore commented on app/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsController.scala
> +                  Redirect(CheckYourBenefitsController.show(taxYear, employmentId))
good idea

2021-11-10 08:39 UTC, joeyymoore commented on it/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsControllerISpec.scala
> +        "render the 'Did you get any benefits for other services' page with the correct content without pre-filled form" which {
wow that was lazy of me, good spot

2021-11-10 08:39 UTC, joeyymoore commented on it/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsControllerISpec.scala
> +        "render the 'Did you get any benefits for other services' page with the correct content with yes value pre-filled" which {
wow that was lazy of me, good spot

2021-11-10 08:39 UTC, joeyymoore commented on it/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsControllerISpec.scala
> +        "render the 'Did you get any benefits for other services' page with the correct content with no value pre-filled" which {
wow that was lazy of me, good spot

2021-11-10 08:39 UTC, joeyymoore commented on it/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsControllerISpec.scala
> +        "should render 'Did you get any benefits for other services' page with empty error text when there no input" which {
wow that was lazy of me, good spot

2021-11-10 08:40 UTC, joeyymoore commented on it/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsControllerISpec.scala
> +          Some(s"/income-through-software/return/employment-income/$taxYearEOY/check-employment-benefits?employmentId=$employmentId")
good idea

2021-11-10 08:46 UTC, HarryGull approved these changes

2021-11-10 09:00 UTC, merged