SASS-1845 Updated save and continue for benefits and updated method t…
hmrc/income-tax-employment-frontend pull request #273
Opened 2022-01-20 16:45 UTC by BenCosfordHMRC

…o work for SL

https://jira.tools.tax.service.gov.uk/browse/SASS-1845

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2022-01-24 10:03 UTC, matt712 commented
uk.gov.hmrc: bootstrap-frontend-play-28 and  uk.gov.hmrc: bootstrap-test-play-28 could be bumped to 5.20.0

2022-01-27 10:21 UTC, ina-tu requested changes
- coverage is a bit low for StudentLoansCYAModel
- needs a rebase

2022-01-27 10:21 UTC, ina-tu commented on it/controllers/employment/CheckYourBenefitsControllerISpec.scala
>  import models.employment.createUpdate.{CreateUpdateEmployment, CreateUpdateEmploymentData, CreateUpdateEmploymentRequest, CreateUpdatePay}
unused imports

2022-01-27 10:21 UTC, ina-tu commented on test/services/EmploymentSessionServiceSpec.scala
> +          true,
name boolean parameters warnings

2022-01-27 11:27 UTC, ina-tu approved these changes

2022-01-27 11:39 UTC, merged