SASS-1938 Create are you sure you want to remove your expenses page
hmrc/income-tax-employment-frontend pull request #298
Opened 2022-02-07 11:38 UTC by walesoares

### Description
Expenses - Create the 'Are you sure you want to remove your expenses

Add a link to the relevant story in Jira
[SASS-1938](https://jira.tools.tax.service.gov.uk/browse/SASS-1938)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [x]  Have you run the tests?
- []  Have you run the journey tests? (where applicable)
- [x]  Have you addressed warnings where appropriate?
- [x]  Have you rebased against the current version of main?
- [x]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2022-02-09 13:27 UTC, BenCosfordHMRC requested changes

2022-02-09 13:27 UTC, BenCosfordHMRC commented on app/services/expenses/RemoveExpensesService.scala
> +  def deleteOrIgnoreExpenses(employmentData: AllEmploymentData, taxYear: Int)(result: Result)
don't think this service is needed, can call the existing deleteOrIgnoreExpenses method in DeleteOrIgnoreExpensesService.

2022-02-15 11:38 UTC, ina-tu requested changes
needs a rebase

2022-02-15 11:38 UTC, ina-tu commented on app/controllers/expenses/RemoveExpensesController.scala
> +                                          professionalFeesAndSubscriptionsExpensesView: ProfessionalFeesAndSubscriptionsExpensesView,
professionalFeesAndSubscriptionsExpensesView can be removed

2022-02-15 11:38 UTC, ina-tu commented on app/views/expenses/RemoveExpensesView.scala.html
> +        @heading(headingForUse, Some(messages("expenses.caption", (taxYear - 1).toString, taxYear.toString)), "govuk-!-margin-bottom-3")
the screenshots show the caption as "Employment for.." instead of "Employment expenses for..."

2022-02-15 11:38 UTC, ina-tu commented on it/controllers/expenses/RemoveExpensesControllerISpec.scala
> +        "redirect to the overview page" when {
this can be moved outside of the userScenarios.foreach loop

2022-02-15 11:38 UTC, ina-tu commented on it/controllers/expenses/RemoveExpensesControllerISpec.scala
> +    userScenarios.foreach { user =>
I think the userScenarios.foreach loop can be taken out since you're not checking for content on the page

2022-02-16 09:30 UTC, ina-tu approved these changes

2022-02-16 09:30 UTC, ina-tu requested changes
needs a rebase

2022-02-16 10:56 UTC, ina-tu approved these changes

2022-02-16 10:58 UTC, BenCosfordHMRC approved these changes

2022-02-16 11:00 UTC, merged