Sass 5590
hmrc/income-tax-employment-frontend pull request #461
Opened 2023-09-21 09:50 UTC by SamuelTwumBarima

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2023-09-21 15:12 UTC, kannanramakrishnan commented on test/views/offPayrollWorking/EmployerOffPayrollWorkingViewSpec.scala
> +    override val expectedRadioHeading: String = "Does your client agree with ABC Digitals decision?"
Required individual heading

2023-09-21 15:13 UTC, kannanramakrishnan commented on app/views/offPayrollWorking/EmployerOffPayrollWorkingView.scala.html
> +        <a href=https://www.gov.uk/government/publications/gains-on-uk-life-insurance-policies-hs320-self-assessment-helpsheet/hs320-gains-on-uk-life-insurance-policies-2022
Href Link is incorrect

2023-09-21 15:14 UTC, kannanramakrishnan commented on test/views/offPayrollWorking/EmployerOffPayrollWorkingViewSpec.scala
> +    override val expectedTitle: String = "Off-payroll working (IR35)"
expected Title and heading are common expected

2023-09-21 15:16 UTC, kannanramakrishnan commented on test/views/offPayrollWorking/EmployerOffPayrollWorkingViewSpec.scala
> +    override val expectedErrorTitle = s"Error: $expectedTitle"
move this to common expected

2023-09-21 15:28 UTC, kannanramakrishnan requested changes
Please update the mentioned comments and also the dependencies.

2023-09-21 15:36 UTC, SamuelTwumBarima commented on test/views/offPayrollWorking/EmployerOffPayrollWorkingViewSpec.scala
> +    override val expectedRadioHeading: String = "Does your client agree with ABC Digitals decision?"
done

2023-09-21 15:36 UTC, SamuelTwumBarima commented on app/views/offPayrollWorking/EmployerOffPayrollWorkingView.scala.html
> +        <a href=https://www.gov.uk/government/publications/gains-on-uk-life-insurance-policies-hs320-self-assessment-helpsheet/hs320-gains-on-uk-life-insurance-policies-2022
done

2023-09-22 09:49 UTC, kannanramakrishnan commented
Coverage for EmployerOffPayrollWorkingController is 83%, which will be addressed part of navigation story SASS-5543 as more focus on this story is to render the view with appropriate english and welsh content for individual page.

2023-09-22 09:49 UTC, kannanramakrishnan approved these changes

2023-09-22 09:49 UTC, merged