[SASS-5591: Create "warning page - Off-payroll working status?" page - OPW]
hmrc/income-tax-employment-frontend pull request #463
Opened 2023-09-22 13:23 UTC by shehzad-ismail8

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2023-09-22 15:11 UTC, kannanramakrishnan requested changes
please check and update review comments

2023-09-25 08:02 UTC, shehzad-ismail8 commented on app/controllers/offPayrollWorking/ChangeYourEmploymentDetailsController.scala
> +    val headingIndividual = "employment.employerOpw.warning.heading.individual"
Amended

2023-09-25 08:02 UTC, shehzad-ismail8 commented on conf/messages
> +employment.employerOpw.warning.button = Confirm
Amended

2023-09-25 08:02 UTC, shehzad-ismail8 commented on conf/messages.cy
> +employment.employerOpw.warning.button = Cadarnhau
Amended

2023-09-25 13:50 UTC, kannanramakrishnan approved these changes

2023-09-26 08:40 UTC, closed without merging