SASS-1034 - Rework Employment details summary page for EOY functionality
hmrc/income-tax-employment-frontend pull request #56
Opened 2021-07-20 11:18 UTC by ina-tu

### Description
Added 'not started' status tags for benefits EOY and updated tests.

Add a link to the relevant story in Jira
[SASS-931](https://jira.tools.tax.service.gov.uk/browse/SASS-931)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of master?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current master that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of master?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2021-07-20 13:57 UTC, ina-tu commented
PR for stub: https://github.com/hmrc/income-tax-submission-stub/pull/55

2021-07-22 09:50 UTC, ina-tu commented
stub pr: https://github.com/hmrc/income-tax-submission-stub/pull/56

2021-07-26 11:12 UTC, michael-rob-poole requested changes

2021-07-26 11:12 UTC, michael-rob-poole commented on app/services/EmploymentSessionService.scala
> +              case _ => false
same as above

2021-07-28 11:09 UTC, BenCosfordHMRC commented on app/services/EmploymentSessionService.scala
> +          val hmrcEmploymentIds = hmrcData.map(_.employmentId)
- hmrcData filter filters out hmrc data that has been ignored that we should exclude from the list. 
- customerOverrideData filters where there are employments that have been overridden and thus need to compare against hmrc data for the latest. 
- newCustomerData is the inverse of that so only has new customer added data. 
- hmrcOverriddenData like customerOverrideData is filtered hmrc data that does have customer override data linked to it (same employmentId) so this set of data needs comparing to customerOverrideData.
- onlyHmrcData is hmrc data that hasn't been overridden (no matching customer data)

At the end the onlyHmrcData & newCustomerData should be in the final list and then will compare the hmrcOverriddenData & customerOverrideData to bring back to latest data.

2021-07-28 11:10 UTC, BenCosfordHMRC commented on app/models/employment/EmploymentExpenses.scala
> +}
The method could be moved into a util method and refactored to reuse the same method for both & will need a test for it - can add to another branch for this.

2021-07-28 11:11 UTC, BenCosfordHMRC commented on app/services/EmploymentSessionService.scala
> +        case _ => false
in the unlikely event that there is no submitted on date for either I figure that it's safer to display the customer as the latest data set as hmrc is very unlikely to be updated for EOY.

2021-07-28 11:11 UTC, BenCosfordHMRC commented on app/services/EmploymentSessionService.scala
> +              case _ => false
same response as above :)

2021-07-28 11:20 UTC, michael-rob-poole commented on app/services/EmploymentSessionService.scala
> +        case _ => false
ok - yeah fair enough but what if there is hmrc data but no customer data? Again, unlikely I know

2021-07-28 11:28 UTC, BenCosfordHMRC commented on app/services/EmploymentSessionService.scala
> +        case _ => false
if there is hmrc data but no customer it will never call this method as this is only for getting the latest data when both sets are present

2021-07-28 11:31 UTC, michael-rob-poole commented on app/services/EmploymentSessionService.scala
> +        case _ => false
Yep - good point

2021-07-28 13:05 UTC, merged