Sass 932
hmrc/income-tax-employment-frontend pull request #61
Opened 2021-07-27 11:19 UTC by lz1kwn

### Description
Created page to include errors and routing

Add a link to the relevant story in Jira
https://jira.tools.tax.service.gov.uk/browse/SASS-932

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of master?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current master that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of master?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2021-07-28 10:09 UTC, matt712 commented
uk.gov.hmrc:play-frontend-hmrc could be bumped to 0.86.0-play-28

2021-07-28 13:30 UTC, matt712 reviewed
Test coverage also. seems like it's slightly down from master. I'm not sure why

2021-07-28 13:30 UTC, matt712 commented on app/controllers/employment/AddEmploymentController.scala
> +        case Right(IncomeTaxUserData(None)) => f
I'd maybe rename "f" here. It kind of makes sense, but it's hard to read and looks weird

2021-07-28 14:29 UTC, BenCosfordHMRC requested changes

2021-07-28 14:29 UTC, BenCosfordHMRC commented on app/common/SessionValues.scala
> +  val EMPLOYMENT_ID = ""
could this be updated to have the name be the same as the value and be more explicit that it's a temporary employment id in session. 

So could be val TEMP_NEW_EMPLOYMENT_ID = "TEMP_NEW_EMPLOYMENT_ID"

2021-07-29 12:16 UTC, matt712 approved these changes

2021-07-29 13:04 UTC, BenCosfordHMRC commented
> Test coverage also. seems like it's slightly down from master. I'm not sure why!

[Uploading Screenshot 2021-07-29 at 14.01.57.png…]()

2021-07-30 14:28 UTC, BenCosfordHMRC approved these changes

2021-07-30 14:33 UTC, merged